import fs from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
import {NullEngine} from '@babylonjs/core/Engines/nullEngine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial.js';
import {MirrorTexture} from '@babylonjs/core/Materials/Textures/mirrorTexture.js';
import {VertexBuffer} from '@babylonjs/core/Buffers/buffer.js';
import {createRainPuddles} from '../src/city-rain-puddles.ts';
import {terrainHeight} from '../src/landmark-details.ts';
const city=JSON.parse(await fs.readFile('public/city/city.json','utf8'));const terrain=JSON.parse(await fs.readFile('public/city/terrain-detail.json','utf8'));const heightAt=(x,z)=>terrainHeight(terrain.grid,x,z);
const detail=JSON.parse(await fs.readFile('public/city/landmark-detail.json','utf8'));const excluded=new Set(detail.baseBuildingIds);city.buildings=city.buildings.filter(b=>!excluded.has(b.id));for(const p of detail.collisionFootprints)city.buildings.push({...p,height:1,style:'landmark-detail'});
const start=performance.now();const packed=JSON.parse(await fs.readFile('artifacts/city/rain-puddles-candidate/puddles-layout.json','utf8'));const pools=[];for(let i=0;i<packed.values.length;i+=10){const [x,z,dx,dz,length,width,lateral,roadWidth,seed,alpha]=packed.values.slice(i,i+10);pools.push({id:'rain-'+i/10,roadId:'prevalidated',kind:'gutter',x,z,dx,dz,length,width,lateral,roadWidth,seed,alpha,outline:[]});}const layout={pools,stats:packed.stats};const layoutMs=performance.now()-start;
const errors=[];const expect=(v,s)=>{if(!v)errors.push(s);};
expect(layout.pools.length>500,'Real-city layout too sparse.');expect(packed.coverage.fraction>=.25&&packed.coverage.fraction<=1/3,'Actual road-union water coverage outside 25–33%.');expect(packed.coverage.outsideEligibleM2===0,'Water overlaps excluded surfaces.');
const engine=new NullEngine({renderWidth:32,renderHeight:32});const scene=new Scene(engine);const mirror=new MirrorTexture('existing-road-mirror',64,scene,true);const existingRoad=new PBRMaterial('existing-road-material',scene);const textureCount=scene.textures.length;
const controller=createRainPuddles(scene,city,heightAt,mirror,layout);await controller.readyPromise;const s=city.spawn;controller.update(s.x,s.z,4);const driving=controller.stats;
const extraTextureCount=scene.textures.length-textureCount;
expect(extraTextureCount===1,'Controller should create exactly one micro-normal texture.');expect(driving.shown>0,'No pools near spawn.');expect(driving.drawCalls<=2,'Too many draw calls.');expect(driving.activeTriangles<=50000,'Near geometry budget exceeded.');expect(driving.shown>400,'Spawn coverage is being capped again.');
const sameFocusRebuilds=controller.stats.rebuilds;controller.update(s.x+1,s.z,4);expect(controller.stats.rebuilds===sameFocusRebuilds,'Geometry is rebuilding every frame.');
const water=controller.meshes[1];expect(water.material.reflectionTexture===mirror,'Puddle material must reuse provided mirror.');
let validTriangles=0,downwardTriangles=0;
for(const mesh of controller.meshes){const p=mesh.getVerticesData(VertexBuffer.PositionKind),ind=mesh.getIndices();for(let i=0;i<ind.length;i+=3){const a=ind[i]*3,b=ind[i+1]*3,c=ind[i+2]*3;const y=(p[b+2]-p[a+2])*(p[c]-p[a])-(p[b]-p[a])*(p[c+2]-p[a+2]);if(Math.abs(y)>1e-10){validTriangles++;if(y<0)downwardTriangles++;}}}
expect(validTriangles>0&&downwardTriangles===0,'Pool winding must face upward.');
controller.update(s.x,s.z,250);const drone=controller.stats;expect(drone.drawCalls<=2&&drone.shown<=5000,'Drone budget exceeded.');
controller.update(s.x,s.z,850);const highOverview=controller.stats;expect(highOverview.drawCalls<=1,'High overview should only show damp patches.');
controller.dispose();expect(scene.textures.includes(mirror),'Puddle disposal destroyed shared mirror.');
let fallbackRequests=0;const originalFetch=globalThis.fetch;globalThis.fetch=async()=>{fallbackRequests++;throw Error('CPU forced missing asset');};const recovering=createRainPuddles(scene,city,heightAt,mirror);recovering.update(s.x,s.z,4);await recovering.readyPromise;expect(recovering.stats.status==='fallback'&&recovering.stats.shown>0,'Missing layout must retain a validated spawn fallback.');globalThis.fetch=async()=>({ok:true,json:async()=>packed});await recovering.retry();expect(recovering.stats.status==='ready'&&recovering.stats.shown>400,'Retry must recover the full validated layout.');recovering.dispose();globalThis.fetch=originalFetch;
const report={fallbackRequests,timestamp:new Date().toISOString(),scope:'CPU-only city layout and Babylon NullEngine geometry/material contract checks. No browser/GPU/visual/60FPS claim.',layoutMs,layout:layout.stats,wetFraction:packed.coverage.fraction,driving,drone,highOverview,extraTextureCount,validTriangles,downwardTriangles,spawnPoolExamples:layout.pools.map(p=>({...p,distanceToSpawn:Math.hypot(p.x-s.x,p.z-s.z)})).sort((a,b)=>a.distanceToSpawn-b.distanceToSpawn).slice(0,8),errors};
await fs.mkdir('artifacts/city/rain-puddles',{recursive:true});await fs.writeFile('artifacts/city/rain-puddles/cpu-check.json',JSON.stringify(report,null,2));console.log(JSON.stringify({layoutMs,layout:layout.stats,wetFraction:report.wetFraction,driving,drone,highOverview,validTriangles,downwardTriangles,errors},null,2));mirror.dispose();scene.dispose();engine.dispose();if(errors.length)process.exitCode=1;
