import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';
import {Matrix,Plane,Vector3} from '@babylonjs/core';
import {BUILDING_SIGN_SHADERS,selectBuildingSigns,stableBuildingSignSet,validateBuildingSignManifest} from '../src/city-building-signs.ts';
import {generateSignage,usefulName,choosePlacement} from './generate_city_building_signs.mjs';
const manifest=JSON.parse(await fs.readFile('artifacts/building-signs/building-signs.json','utf8')),city=JSON.parse(await fs.readFile('public/city/city.json','utf8')),raw=JSON.parse(await fs.readFile('data/processed/shenzhen_study/buildings.geojson','utf8')),exclusions=JSON.parse(await fs.readFile('public/city/building-exclusions.json','utf8')).excludedIds;
assert(validateBuildingSignManifest(manifest));const regenerated=generateSignage(city,raw.features,exclusions);assert(JSON.stringify(regenerated.signs)===JSON.stringify(manifest.signs),'same source yields byte-stable serialized names, geometry and artwork choices');
const unique=new Map(city.buildings.map(b=>[b.id,b])),named=manifest.signs.filter(s=>s.kind==='osm-building-name'),fictional=manifest.signs.filter(s=>s.kind==='fictional-game-business');
assert.equal(new Set(manifest.signs.map(s=>s.buildingId)).size,manifest.signs.length);assert(manifest.signs.length/unique.size>=.20);
for(const s of named){assert.equal(s.text,unique.get(s.buildingId).name,'never invent or shorten real names');assert(s.source?.featureId===s.buildingId);}
for(const s of fictional)assert.equal(s.fictionalDisclosure,'深城纪·虚构品牌');
for(const text of ['1栋','A座','12栋A座','3-2栋','办公楼','教学楼'])assert(!usefulName(text));for(const text of ['腾讯滨海大厦','赛格广场','深业上城'])assert(usefulName(text));
for(const s of manifest.signs){assert(!exclusions.includes(s.buildingId));assert(s.position[1]+s.height/2<=s.buildingHeight+.1);assert(s.position[1]/s.buildingHeight>=.65);assert(s.width>0&&s.height>0);}
const rect={rings:[[[0,0],[30,0],[30,20],[0,20],[0,0]]],height:80};for(const seed of [1,4,7,33,127]){const s=choosePlacement(rect,'示例大厦',seed);assert(s);const dx=s.position[0]-15,dz=s.position[2]-10;assert(dx*s.normal[0]+dz*s.normal[2]>0,'sign faces outward from simple footprint');}
const focus={x:city.spawn.x,y:6,z:city.spawn.z},near=selectBuildingSigns(manifest.signs,focus);assert(near.length<=64);assert(near.every(s=>Math.hypot(s.position[0]-focus.x,s.position[1]-focus.y,s.position[2]-focus.z)<1100));assert.deepEqual(stableBuildingSignSet(near),stableBuildingSignSet([...near].reverse()),'distance ranking changes alone cannot move atlas slots');
const selectionEye={x:0,y:0,z:0},selectionView={viewProjection:Matrix.LookAtLH(Vector3.Zero(),new Vector3(0,0,1),Vector3.Up()).multiply(Matrix.PerspectiveFovLH(.9,16/9,.1,2000)),forward:new Vector3(0,0,1),pixelScale:1000};
const sample=manifest.signs[0],selectionSamples=[{...sample,id:'front',position:[0,0,100],normal:[0,0,-1]},{...sample,id:'backface',position:[0,0,90],normal:[0,0,1]},{...sample,id:'offscreen',position:[400,0,100],normal:[0,0,-1]},{...sample,id:'behind-eye',position:[0,0,-100],normal:[0,0,1]},{...sample,id:'unreadable',position:[0,0,900],height:.1,normal:[0,0,-1]}];
assert.deepEqual(selectBuildingSigns(selectionSamples,selectionEye,64,1100,selectionView).map(s=>s.id),['front'],'near backfaces, offscreen signs and subpixel letters must not consume atlas slots');
const eye=new Vector3(10,7,-20),view=Matrix.LookAtLH(eye,new Vector3(0,5,0),Vector3.Up()),reflection=Matrix.Reflection(new Plane(0,1,0,0)),mirrorView=reflection.multiply(view),inverse=mirrorView.invert(),renderEye=inverse.getTranslation(),expectedEye=Vector3.TransformCoordinates(eye,reflection);assert(Vector3.Distance(renderEye,expectedEye)<1e-5,'inverse current view supplies mirrored eye');assert(Vector3.Distance(renderEye,eye)>10);
const compilerJS=await fs.readFile('node_modules/@babylonjs/core/assets/glslang/glslang.js','utf8'),wasm=await fs.readFile('node_modules/@babylonjs/core/assets/glslang/glslang.wasm'),diagnostics=[],context={module:{exports:{}},exports:{},window:{},document:{currentScript:{src:'local://glslang.js'}},WebAssembly,TextDecoder,TextEncoder,setTimeout,clearTimeout,console:{log:(...x)=>diagnostics.push(x.join(' ')),warn:(...x)=>diagnostics.push(x.join(' ')),error:(...x)=>diagnostics.push(x.join(' '))},fetch:async()=>new Response(wasm,{headers:{'Content-Type':'application/wasm'}})};vm.runInNewContext(compilerJS,context);const compiler=await context.module.exports('local://glslang.wasm');
const varyings={vUV:0,vPosition:1,vNormal:2,vColor:3,vLetterSize:4},attrs={position:0,normal:1,uv:2,color:3,letterSize:4};
let vertex=BUILDING_SIGN_SHADERS.vertex.replace(/attribute (\w+) (\w+);/g,(_,t,n)=>`layout(location=${attrs[n]}) in ${t} ${n};`).replace(/varying (\w+) (\w+);/g,(_,t,n)=>`layout(location=${varyings[n]}) out ${t} ${n};`).replace('uniform mat4 worldViewProjection;','layout(binding=0) uniform View {mat4 worldViewProjection;};');
let fragment=BUILDING_SIGN_SHADERS.fragment.replace(/varying (\w+) (\w+);/g,(_,t,n)=>`layout(location=${varyings[n]}) in ${t} ${n};`).replace('uniform sampler2D lettering;','layout(binding=1) uniform sampler2D lettering;').replace('uniform vec3 signEyePosition;uniform float night;uniform float pixelScale;uniform float maxDistance;','layout(binding=0) uniform Frame {vec3 signEyePosition;float night;float pixelScale;float maxDistance;};').replace('texture2D(','texture(').replace('gl_FragColor=','outputColor=');
vertex='#version 450\n'+vertex;fragment='#version 450\nlayout(location=0) out vec4 outputColor;\n'+fragment;const words={vertex:compiler.compileGLSL(vertex,'vertex').length,fragment:compiler.compileGLSL(fragment,'fragment').length};
assert(words.vertex>0&&words.fragment>0);const source=await fs.readFile('src/city-building-signs.ts','utf8');assert.match(source,/scene.getViewMatrix\(\).invertToRef\(inverseView\)/);assert(!source.includes("setVector3('cameraPosition'"));
const report={passed:true,gpu:false,counts:manifest.stats,nearAtSpawn:near.length,offlineGLSLWords:words,checks:['exact source-name preservation','no duplicate building id','stable seed placement/style and deterministic regeneration','20% independent-building coverage with explicitly fictional supplementation','generic number-only names excluded','authored landmark exclusion ids respected','outward facade normals and top height bounds','64-visible/distance LOD bound','front-facing/main-frustum/minimum letter pixel selection','stable set atlas ordering','per-render inverse-view mirror eye','actual vertex/fragment GLSL offline compilation'],boundary:'No GPU, build, live canvas typography or visual placement validation was run.'};await fs.writeFile('artifacts/building-signs/cpu-check.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
