/** Runtime contract for public/city/vehicle-manifest.json. Generated by
 * scripts/optimize_vehicle_candidate.mjs and audited by scripts/check_vehicle_delivery.mjs;
 * third-party cars may hand-write it, so every optional field degrades gracefully. */
export type V3=[number,number,number];
export type VehicleManifest={
 wheelRadius:number;
 wheelCentresGltf:Record<string,V3>;
 /** Two game-frame headlight positions (x right, y up, z forward, metres). */
 recommendedHeadlightAnchorsGame?:V3[];
};

/** Third-party cars ship a manifest with only wheelRadius/wheelCentresGltf; a missing
 * headlight field used to crash loading at stage 09/17 with an unreadable `.slice` error
 * (GTA_SZ#2). Fall back to the hero car's anchors near the two front corners. */
export const DEFAULT_HEADLIGHT_ANCHORS:readonly [number,number,number][]=[[-.7,.79,2.36],[.7,.79,2.36]];
export function headlightAnchors(anchors:unknown):[number,number,number][]{
 const valid=Array.isArray(anchors)&&anchors.length>=2&&anchors.slice(0,2).every(a=>Array.isArray(a)&&a.length===3&&a.every(Number.isFinite));
 if(!valid&&anchors!==undefined)console.warn('vehicle-manifest.json: recommendedHeadlightAnchorsGame 缺失或无效，使用默认前灯锚点',anchors);
 return (valid?(anchors as [number,number,number][]).slice(0,2):DEFAULT_HEADLIGHT_ANCHORS.map(a=>[...a] as [number,number,number]));
}
